# Primeira Avaliação Parcial: Avaliação Individual

Neste módulo trabalhamos com os recursos da __NumPy__ para processar dados de tipo único de forma eficiente. Um exemplo deste tipo de dados são as imagens que podemos ser armazenadas como _ndarrays_ __NumPy__. O código a seguir gera uma imagem colorida, de 1000 por 1000 _pixels_, armazenada no formato __RGB__. Isto significa que, de cada _pixel_ armazenamos a intensidade de cor nos canais __R__ (_red_ ou vermelho), __G__ (green ou verde) e __B__ (blue o azul).  A intensidade da cor é dada por um inteiro de 8 _bits_ sem sinal.

In [73]:
# importado a biblioteca numpy
import numpy as np
print(np.__version__)

1.24.3


In [74]:
# Definindo a altura e a largura da imagem
height = 1000  # altura ou o número de linhas da imagem
width = 1000   # largura ou o número de colunas da imagem

In [75]:
# gerando uma imagem aleatória de 1000 x 1000 pixels
random_image = np.random.randint(0, 256, size=(height, width, 3), dtype=np.uint8)
print("Veja o forma da matriz criada: {}".format(random_image.shape))
print("Veja como fica a cor de um pixel: {} ...".format(random_image[0, 0]))
print("Ou a componente vermelha dos 3 primeiro pixels da segunda linha: {} ...".format(random_image[1, 0:3, 0]))
print("Ou a componente verde dos 3 últimos pixels da segunda coluna: {} ...".format(random_image[-3:, 1, 1]))

Veja o forma da matriz criada: (1000, 1000, 3)
Veja como fica a cor de um pixel: [ 39 247  11] ...
Ou a componente vermelha dos 3 primeiro pixels da segunda linha: [154 108 172] ...
Ou a componente verde dos 3 últimos pixels da segunda coluna: [241 157 227] ...


## Exercício 1

Crie uma função para a qual passamos como parâmetros a altura e a largura e retorna uma imagem, gerada de forma aleatória, em formato __RGB__, com estas dimensões. A imagem deve ser representada utilizando um _ndarray_ como o do exemplo anterior. Se a altura ou a largura não forme passadas como a imagem deve ser gerada com 720 linhas e 1280 colunas. 

In [76]:
# Implementar aqui
def geradorImagens(altura = 720, largura = 1280):
    imagem = np.random.randint(0, 256, size=(altura, largura, 3), dtype=np.uint8)
    return imagem

In [77]:
#teste
print(geradorImagens().shape) # deve retornar (720, 1280, 3)
print(geradorImagens(10).shape) # deve retornar (10, 1280, 3)
print(geradorImagens(10,10).shape) # deve retornar (10, 10, 3)
print(geradorImagens(5,5)) # deve retornar uma matriz 5x5x3

(720, 1280, 3)
(10, 1280, 3)
(10, 10, 3)
[[[142 100 138]
  [232 105 197]
  [214 142 238]
  [ 11  91 118]
  [140 181  86]]

 [[ 11 190 131]
  [212 172 159]
  [164  32  51]
  [131 213 133]
  [ 45  99 119]]

 [[205  18  82]
  [ 69   7 214]
  [ 20  11  82]
  [202 107  68]
  [171 231 147]]

 [[ 67  82  21]
  [ 25 243 108]
  [192  85 145]
  [183  21 155]
  [ 23 117 183]]

 [[214 234 145]
  [215  90 113]
  [202 167 200]
  [ 27 209  19]
  [102 204  19]]]


Para simplificar o tratamento durante o processamento das imagens, frequentemente elas são convertidas e imagens em tons de cinza. Estas imagens contem, para cada pixel, uma única intensidade de cor representada como um inteiro de 8 _bits_ sem sinal. Para converter uma imagem __RGB__ em uma imagem em tons de cinza podemos utilizar dois métodos diferentes. 

1. Calculamos a intensidade da cor de cada _pixel_ como a média das intensidades dos canais __RGB_
2. Os valores __RGB__ são convertidos para tons de cinza usando a fórmula __NTSC__: $ 0.299 \times \text{Vermelho} + 0.587 \times \text{Verde} + 0.114 \times \text{Azul} $. Esta fórmula representa de perto a percepção relativa da pessoa média sobre o brilho da luz vermelha, verde e azul.

## Exercício 2

Crie uma função que recebe uma imagem __RGB__ e converte a mesma em tons de cinza. A função deve retornar então a nova imagem. Esta função. 
* Deve verificar se o argumento de entrada é de fato uma imagem __RGB__ com base no tipo e no atributo ``shape`` do _ndarray_. Casso o argumento esteja errado deve-se lançar uma exceção.
* A função recebe como parâmetro de entrada a forma de conversão a ser utilizada: media dos canais ou __NTSC__. Por padrão o algoritmo de utilizado deve ser o __NTSC__.
* A função deve utilizas as _ufunc_ e operações definidas na __NumPy_ de forma a minimizar o uso de laços no processamento dos _ndarrays_.  

In [78]:

#implementar aqui
def rgb2gray(imagem, conversao = "NTSC"):
    
    # verificação de parametros
    shape = imagem.shape
    if len(shape) != 3 or shape[2] != 3 or imagem.dtype != np.uint8:
        raise ValueError("Parametro nao é uma imagme RGB no formato uint8")
    if conversao != "NTSC" and conversao != "media":
        raise ValueError("Parametro conversao deve ser NTSC ou 'media' (media de canais)")
    
    # conversao
    if conversao == "NTSC":
        imagem_convertida = (0.299 * imagem[:,:,0]) + (0.587 * imagem[:,:,1]) + (0.114 * imagem[:,:,2])
    else:
        imagem_convertida = np.mean(imagem, axis=2)
    return imagem_convertida.astype(np.uint8)
    
    

In [79]:
# teste de exeções

# tipo de converao invalido
try:
    rgb2gray(np.zeros((10,10,3), dtype=np.uint8), "teste")
except Exception as e:
    print("Erro: {}".format(e))

# imagem com dimensões invalidas
try:
    rgb2gray(np.zeros((10,10,4), dtype=np.uint8))
except Exception as e:
    print("Erro: {}".format(e))
    
# imagem com tipo invalido
try:
    rgb2gray(np.zeros((10,10,3), dtype=np.float32))
except Exception as e:
    print("Erro: {}".format(e))

Erro: Parametro conversao deve ser NTSC ou 'media' (media de canais)
Erro: Parametro nao é uma imagme RGB no formato uint8
Erro: Parametro nao é uma imagme RGB no formato uint8


In [80]:
# teste de conversa
imagem = geradorImagens(2,2)
print("RGB")
print(imagem)

print("\nNTSC")
imagem_cinza = rgb2gray(imagem, "NTSC")
print(imagem_cinza)

print("\nMedia")
imagem_cinza = rgb2gray(imagem, "media")
print(imagem_cinza)

RGB
[[[ 60  97 144]
  [174  48 211]]

 [[241 163 122]
  [120  88 213]]]

NTSC
[[ 91 104]
 [181 111]]

Media
[[100 144]
 [175 140]]


# Exercício 3 (Opcional, valendo ponto extra)

Refaça a implementação da função anterior utilizando estruturas de repetição e implemente um teste de demonstre, usando uma imagem __RGB__ gerada de forma aleatória de 10.000 linhas por 10.000 colunas, o ganho de desempenho quando utilizamos as _ufunc_ e os operadores de __NumPy__. 

In [81]:
# gerando uma imagem aleatória de 10000 x 10000 pixels
imagem = geradorImagens(10000,10000)

In [82]:
#implementar aqui
def rgb2gray_repeticao(imagem, conversao = "NTSC"):
    
    # verificação de parametros
    shape = imagem.shape
    if len(shape) != 3 or shape[2] != 3 or imagem.dtype != np.uint8:
        raise ValueError("Parametro nao é uma imagme RGB no formato uint8")
    if conversao != "NTSC" and conversao != "media":
        raise ValueError("Parametro conversao deve ser NTSC ou 'media' (media de canais)")
    
    # conversao
    if conversao == "NTSC":
        for i in range(shape[0]):
            for j in range(shape[1]):
                imagem[i,j,0] = (0.299 * imagem[i,j,0]) + (0.587 * imagem[i,j,1]) + (0.114 * imagem[i,j,2])
    else:
        for i in range(shape[0]):
            for j in range(shape[1]):
                imagem[i,j,0] = (imagem[i,j,0] + imagem[i,j,1] + imagem[i,j,2])/3
    return imagem[:,:,0].astype(np.uint8)

### Comparação de desempenho

1. Metodo NTSC

In [83]:
%timeit -n 2 -r 2 rgb2gray(imagem, "NTSC")
imagem_cinza_ufunc = rgb2gray(imagem, "NTSC")

1.23 s ± 12.5 ms per loop (mean ± std. dev. of 2 runs, 2 loops each)


In [84]:
%timeit -n 2 -r 2 rgb2gray_repeticao(imagem, "NTSC")
imagem_cinza_repeticao = rgb2gray_repeticao(imagem, "NTSC")

KeyboardInterrupt: 

In [ ]:
# teste de igualdade
print(np.allclose(imagem_cinza_ufunc, imagem_cinza_repeticao))

2. Metodo Media de canais

In [ ]:
%timeit -n 2 -r 2 rgb2gray(imagem, "media")
imagem_cinza_ufunc = rgb2gray(imagem, "media")

In [ ]:
%timeit -n 2 -r 2 rgb2gray_repeticao(imagem, "media")
imagem_cinza_repeticao = rgb2gray_repeticao(imagem, "media")

In [ ]:
# teste de igualdade
print(np.allclose(imagem_cinza_ufunc, imagem_cinza_repeticao))

## Respostas
Faça suas implementações neste notebook e envie  mesmo via __Moodle__ até o final do prazo. 